In [7]:
sudoku=[[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]]

In [8]:
import numpy as np

In [ ]:
def check(row,col,num):
    global sudoku
    for i in range(9):
        if sudoku[i][col] == num:
            return False
        if sudoku[row][i] == num:
            return False

    start_x = (row//3)*3
    start_y = (col//3)*3

    for i in range(0,3):
        for j in range(0,3):
            if sudoku[start_x+i][start_y+j] == num:
                return False
    return True

In [ ]:
print(check(6,0,4))

In [10]:
def SudokuSolver():
    global sudoku
    for i in range(0,9):
        for j in range(0,9):
            if sudoku[i][j] == 0:
                for k in range(1,10):
                    if check(i,j,k):
                        sudoku[i][j] = k
                        SudokuSolver()
                        sudoku[i][j] = 0
                return
    print(np.matrix(sudoku))
    input('More?')

In [ ]:
SudokuSolver()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
